// Build-time data generator.
//
// The redesign renders the SAME quest data the live vanilla site ships, so the
// prod file is the single source of truth. We read
// ../ps5-rpg-sidequest-summarizer/data/quests.js (plain declarations, no
// exports), evaluate it, and emit a typed ESM module the React app imports.
// Run automatically via the `predev` / `prebuild` npm hooks.

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROD_DATA = path.resolve(
  __dirname,
  "../../ps5-rpg-sidequest-summarizer/data/quests.js"
);
const OUT = path.resolve(__dirname, "../src/generated/data.ts");

// The deploy publishes the vanilla site under /newapp/classic/, so its images/
// dir lives at /newapp/classic/images/. Use an absolute URL so covers resolve
// no matter where the redesign is hosted (/staging/, /app/, or local dev).
const IMG_BASE = "https://kbarbu12.github.io/newapp/classic/";

// The prod file declares `const gameImages = {...}` and `const quests = [...]`
// with no exports. Append an export line, import it as a temp ESM module.
const src = fs.readFileSync(PROD_DATA, "utf8");
const tmp = path.join(os.tmpdir(), `quests-${Date.now()}.mjs`);
fs.writeFileSync(tmp, `${src}\nexport { quests, gameImages };\n`);
const { quests, gameImages } = await import(pathToFileURL(tmp).href);
fs.unlinkSync(tmp);

// accent = the bright end-stop of each game's gradient.
const lastHex = (g) => {
  const m = String(g).match(/#[0-9a-fA-F]{3,8}/g);
  return m ? m[m.length - 1] : "#c5933a";
};

const GAMES = {};
for (const [name, gi] of Object.entries(gameImages)) {
  GAMES[name] = {
    cover: IMG_BASE + gi.cover.replace(/^\.?\//, ""),
    abbr: gi.abbr,
    accent: lastHex(gi.gradient),
    gradient: gi.gradient,
  };
}

// A "real" walkthrough is a specific video/playlist link. Placeholder search
// links (…/results?search_query=…) don't count — mirror the live site
// (ps5-rpg-sidequest-summarizer/src/app.js:hasRealVideo) so the video filter
// and "With Video" stat match prod.
const hasRealVideo = (v) => !!v && !v.includes("/results");

// Keep only the fields the design consumes.
const QUESTS = quests.map((q) => ({
  id: q.id,
  type: q.type === "main" ? "main" : "side",
  game: q.game,
  title: q.title,
  length: q.length,
  difficulty: q.difficulty,
  summary: q.summary,
  ...(hasRealVideo(q.video) ? { video: q.video } : {}),
  ...(q.reward ? { reward: q.reward } : {}),
  ...(Array.isArray(q.walkthrough) && q.walkthrough.length
    ? { walkthrough: q.walkthrough }
    : {}),
}));

const banner =
  "// AUTO-GENERATED by scripts/gen-data.mjs from the live quest data.\n" +
  "// Do not edit by hand — run `npm run gen:data` (or dev/build) to refresh.\n";

const body =
  banner +
  "\nexport interface Quest {\n" +
  "  id: number; type: \"side\" | \"main\"; game: string; title: string;\n" +
  "  length: \"short\" | \"medium\" | \"long\"; difficulty: \"Low\" | \"Medium\" | \"High\";\n" +
  "  summary: string; video?: string; reward?: string; walkthrough?: string[];\n" +
  "}\n\n" +
  "export interface GameMeta { cover: string; abbr: string; accent: string; gradient: string; }\n\n" +
  `export const GAMES: Record<string, GameMeta> = ${JSON.stringify(GAMES, null, 2)};\n\n` +
  `export const QUESTS: Quest[] = ${JSON.stringify(QUESTS, null, 2)};\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(
  `gen-data: wrote ${QUESTS.length} quests, ${Object.keys(GAMES).length} games -> ${path.relative(process.cwd(), OUT)}`
);
